### PR TITLE
feat(goto): Navigate between test and implementation

### PR DESCRIPTION
**Pull request by olivernybroe**
This PR adds support for navigating between a test and it's implementation.
image

- [x] Added or updated tests
- [x] Updated `CHANGELOG.md`

issues: #34

### CODE REVIEW

**Comment by olivernybroe** [comment]
Hi @BertvanHoekelen, could I get you to test out if this works and satisfies your issue?

install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
[pest-intellij-0.4.0-alpha.1.zip](https://github.com/pestphp/pest-intellij/files/5084444/pest-intellij-0.4.0-alpha.1.zip)

**Comment by olivernybroe** [comment]
Hey @adelf, could I get you to review the indexer? First time creating one, so would like to know if I made any huge mistakes 😄

**Comment by adelf** [comment]
Hi, @olivernybroe . This index is too greedy. It will try to find pest test functions inside **every** php file during indexing. Better to add at least some filter, for example file path should include "/tests/" part... it can be implemented in InputFilter. I can add it later today.

**Comment by olivernybroe** [comment]
@adelf Ah nice. Yes that makes a lot of sense. So getting directories marked as test and only look at them? 

Looking a little on how `isPestTestFile` works, I also think we can improve that one. The code looks like this for it 
```kotlin
fun PsiFile.isPestTestFile(): Boolean {
    if (this !is PhpFile) return false

    return PsiTreeUtil.findChildrenOfType(this, FunctionReferenceImpl::class.java)
        .any(FunctionReferenceImpl::isPestTestFunction)
}
```

So it basically fetches all FunctionReferences and then checks if one of them is a pest test functions. I was thinking if we could somehow check this with an iterator/tree traverser so it on each FunctionReference checks if they are a pest function and stops if that is true. This way it won't have to traverse the whole tree first and then check each element, but can stop earlier in checking the tree, if it hits a pest test early on. Just now sure how to implement that 😟

**Comment by adelf** [comment]
Fixed. Index tests should try to find a virtual file in the list. Just the key value in the key list.

**Comment by olivernybroe** [comment]
@adelf I updated `InputFilter` so it should limit based on test directory.

It looks if the path contains any test folders, e.g. so it can match 
- `/test/.../MyTest.php`
- `/tests/.../MyTest.php`
`/src/test/.../MyTest.php`

It then also checks all test source folders, so if users have some special setup where the test folder is not called test, but is marked as test, it still works.

Do you see any issues with this?

**Comment by BertvanHoekelen** [comment]
Hi @olivernybroe, I have just installed the alpha and it works like a charm 🎉  Thanks!

**Comment by olivernybroe** [comment]
@BertvanHoekelen Awesome! Thanks for testing it out. 

We will fix some performance issues with it and then I think we will release a new version of the plugin where this feature will be part of it.

**Comment by adelf** [comment]
https://github.com/pestphp/pest-intellij/blob/master/src/main/kotlin/com/pestphp/pest/PestTestFileUtil.kt#L36 here I find all `beforeEach` calls, assuming they are in the top of the file. So:
```<?php
beforeEach(...)
```
Will be found, but 
```<?php
if (...) {
    beforeEach(...)
}
```
this one won't. So, I check only first level of the tree, which of course much faster. If it's ok, we can use the same for `isPestTestFile` method.

**Comment by olivernybroe** [comment]
@adelf Ah that's brilliant! 

Should help a lot with indexing on big files which are not pest tests.

If people have tests which are wrapped in if statements of something like that, then I am okay with not supporting it.

**Comment by olivernybroe** [comment]
@adelf I'll merge this in and make a EAP release for `0.4.0-alpha.2`. 

I think i'll make the `0.4.0` release when you have finished up what you are working on.

**Pull request merged**
