### PR TITLE
feat(runner): Add pcov engine support

### PR DESCRIPTION
**Pull request by olivernybroe**
This pull request adds support for the pcov coverage engine

- [x] Added or updated tests
- [x] Updated `CHANGELOG.md`

issues: #42

### CODE REVIEW

**Comment by olivernybroe** [comment]
The pcov engine runner works, however there are some problems with getting phpstorm to save the settings consistently.

**Comment by olivernybroe** [comment]
@dmason30 Sorry for the delay on this, had some difficulties in regards to getting settings saved correctly.

Could I get your to test this out and see if it works? You should have a setting now to select PCOV.
Also could you test if the settings are still there correctly after a restart. If that works, then I'll release this as the next EAP version and prob. soonish release a new stable version.

To test it out, install the zip file here manually ([docs on manual installation](https://github.com/pestphp/pest-intellij#installation))
[pest-intellij-0.4.0-alpha.8.zip](https://github.com/pestphp/pest-intellij/files/5251284/pest-intellij-0.4.0-alpha.8.zip)

**Comment by dmason30** [comment]
Hi, I have given this a test using both coverage engines works great, settings save perfectly. LGTM!

Thanks for all the work on this Oliver! ❤️

**Comment by olivernybroe** [comment]
@dmason30 Awesome, thanks for testing it out for me 👍

**Pull request merged**
